### ISSUE TITLE
idk i got bug

### ISSUE THREAD

**Issue by Atsuieon** [espidev/ProtectionStones#373] opened 2023-04-27 21:57 UTC
what this mean https://i.imgur.com/DwY3cxI.png

**Comment by espidev** [comment] 2023-05-08 04:01
You can ignore this for the time being, but it's something either I or worldguard will need to address (I haven't investigated)

Duplicate of https://github.com/espidev/ProtectionStones/issues/367

**Closed by espidev** 2023-05-08 04:01 UTC
