### ISSUE TITLE
Merge multiple protection stones into a single 3D polygon!

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#44] opened 2019-08-02 14:05 UTC
Add a toggleable setting to allow to automatically merge multiple protection stones into a single 3D polygon! 

This should happen automatically, when two or more areas generated by the same kind of protection stones are overlapping.

Useful for servers using dynmap, and also to perform commands on just a big polygon instead of on multiple same-sized regions.

**Comment by espidev** [comment] 2019-08-06 22:19
This will be interesting to implement, I'll have to develop some algorithms to do this...

## Tasks
* Develop algorithm to draw new polygon with square edges when given set of points (each as a corner of an existing PS)
* Develop algorithm to merge protection region data, and choose which settings to preserve (merging players, owners, choosing which flag options to take)

The first algorithm will be the hardest to do, so I'll have to brush up on some geometry to figure this out...

Merging regions in WorldGuard isn't even possible right now with the API so if I am able to get this working it'll be really cool lol

**Comment by Leonardo-Fiori** [comment] 2019-08-08 12:17
> This will be interesting to implement, I'll have to develop some algorithms to do this...
> 
> ## Tasks
> * Develop algorithm to draw new polygon with square edges when given set of points (each as a corner of an existing PS)
> * Develop algorithm to merge protection region data, and choose which settings to preserve (merging players, owners, choosing which flag options to take)
> 
> The first algorithm will be the hardest to do, so I'll have to brush up on some geometry to figure this out...
> 
> Merging regions in WorldGuard isn't even possible right now with the API so if I am able to get this working it'll be really cool lol

Yup! You should probably start by googling some math about intersecting cubes and that kind of stuff hahaha it won't be easy i know..

then the easy part once you figured out the intersection points and created the new polygon, will be to assign it the properties of the older region.. and then store somehow that the new polygon is composed by two protection blocks and no more just one.

**Comment by espidev** [comment] 2019-08-10 17:30
This is probably going to be delayed for 2.4.0 since I want to avoid a buggy release, and have the other bug fixes and features out first

**Comment by espidev** [comment] 2019-08-14 19:08
I have an idea to do it, but optimizing the performance will be tricky (maybe try using linear algebra?)

**Comment by espidev** [comment] 2019-08-18 02:01
Merging part is roughly done, still need to work on empty spaces inside merged regions.

Will have to start the unmerge algorithm, which will be much more challenging.

**Comment by Leonardo-Fiori** [comment] 2019-08-18 07:38
@espidev oh gosh when suggesting this I did not imagine that it could take so much effort hahaha

What to do with empty spaces? Prevent merging until all the spaces are covered?

Remember to add the condition that only protection stones of the same size should be merged together, smaller ones should be kept separated from bigger ones and vice versa, so that players can make sub-zones..

P.s. is this cpu-consuming? If yes, is it something that could be pushed to a secondary thread or it needs to be on the main thread? If the plugin starts lagging the whole server when placing a PS it's not a good thing..

**Comment by espidev** [comment] 2019-08-18 19:27
> @espidev oh gosh when suggesting this I did not imagine that it could take so much effort hahaha
> 
> What to do with empty spaces? Prevent merging until all the spaces are covered?
> 
> Remember to add the condition that only protection stones of the same size should be merged together, smaller ones should be kept separated from bigger ones and vice versa, so that players can make sub-zones..
> 
> P.s. is this cpu-consuming? If yes, is it something that could be pushed to a secondary thread or it needs to be on the main thread? If the plugin starts lagging the whole server when placing a PS it's not a good thing..

I've already fixed the empty spaces issue with some tweaks to the algorithm. I've run into limitations with WorldGuard however, since it doesn't support 3D polygons (meaning merged regions will have to protect from 0 to 256 in y).

The way the merging works is that there is now a /ps merge command that allows merging regions, and after a block is placed, it will show the /ps merge GUI menu to confirm region merging. 

I still have to figure out the behaviour when people remove their merged protection stone, and how it will unmerge the regions (as well as confirmation messages for that).

The next step right now though is implementing a new /ps view that uses the convex hull algorithm to draw lines between the point edges since WG doesn't guarantee that the points it gives for a polygon region 

The step after that will be the unmerge algorithm, as well as figuring out how /ps admin recreate will deal with situations where the ps region will have become too small to be merged (possibly just ignore these situations?)

Performance right now is good with the /ps merge stuff being in a separate thread, and the algorithm itself not being too demanding anyway, though I'm worried about unmerging, since that has to take place on the main thread when the player removes the block.

**Comment by espidev** [comment] 2019-08-18 21:58
[https://imgur.com/a/OGkBVXq](url)
Some issues right now with merging but we'll see

**Comment by espidev** [comment] 2019-08-19 20:43
Rewrite of the region system is now ongoing, since there are now different types of PSRegions (and calculating properties for merged regions when unmerging is hard)

**Comment by Leonardo-Fiori** [comment] 2019-08-20 09:23
> ![image](https://camo.githubusercontent.com/4384948b6c362d04f722296c909d4f34dc89314f/68747470733a2f2f692e696d6775722e636f6d2f41523164786e482e706e67)
> Some issues right now with merging but we'll see

lol we have a problem haha



> > @espidev oh gosh when suggesting this I did not imagine that it could take so much effort hahaha
> > What to do with empty spaces? Prevent merging until all the spaces are covered?
> > Remember to add the condition that only protection stones of the same size should be merged together, smaller ones should be kept separated from bigger ones and vice versa, so that players can make sub-zones..
> > P.s. is this cpu-consuming? If yes, is it something that could be pushed to a secondary thread or it needs to be on the main thread? If the plugin starts lagging the whole server when placing a PS it's not a good thing..
> 
> I've already fixed the empty spaces issue with some tweaks to the algorithm. I've run into limitations with WorldGuard however, since it doesn't support 3D polygons (meaning merged regions will have to protect from 0 to 256 in y).
> 
> The way the merging works is that there is now a /ps merge command that allows merging regions, and after a block is placed, it will show the /ps merge GUI menu to confirm region merging.
> 
> I still have to figure out the behaviour when people remove their merged protection stone, and how it will unmerge the regions (as well as confirmation messages for that).
> 
> The next step right now though is implementing a new /ps view that uses the convex hull algorithm to draw lines between the point edges since WG doesn't guarantee that the points it gives for a polygon region
> 
> The step after that will be the unmerge algorithm, as well as figuring out how /ps admin recreate will deal with situations where the ps region will have become too small to be merged (possibly just ignore these situations?)
> 
> Performance right now is good with the /ps merge stuff being in a separate thread, and the algorithm itself not being too demanding anyway, though I'm worried about unmerging, since that has to take place on the main thread when the player removes the block.

Ugh, that limitation really sucks! :/ but i gues that it will also make it easier for you. And probably also for players to understand.. i have to update claim blocks prices so i guess.. 

The important part is to let server owners toggle the merging feature off for some claim block types. For example on my server i use lapis ore as 4x4x4, a very small claim useful to players for making hotel rooms and other little plots for guests.. it would break everything if it claimed from 0 to 255

**Comment by espidev** [comment] 2019-08-20 19:41
Yeah I can't exactly imagine doing the 3D merges though, performance would be pretty terrible and the merging code is already 10-15% of the plugin's code...

After doing further testing, I've simply run into the limitations of WorldGuard...  Technically they don't really support regions with holes inside since the math gets pretty hard to do

**Comment by Leonardo-Fiori** [comment] 2019-08-20 19:47
> Yeah I can't exactly imagine doing the 3D merges though, performance would be pretty terrible and the merging code is already 10-15% of the plugin's code...
> 
> After doing further testing, I've simply run into the limitations of WorldGuard... Technically they don't really support regions with holes inside since the math gets pretty hard to do

Sad story.. so how do you solved the holes inside the region?

**Comment by espidev** [comment] 2019-08-20 19:52
Not sure yet, sometimes it works sometimes it doesn't...
I am currently contacting the WG maintainers to see if this is actually possible lol

**Comment by Leonardo-Fiori** [comment] 2019-08-20 19:55
> Not sure yet, sometimes it works sometimes it doesn't...
> I am currently contacting the WG maintainers to see if this is actually possible lol

Oh crap.. let's hope you did not waste your time programming all this without being possible to make it work. May the old gods of World guard be on your side. lol

**Comment by espidev** [comment] 2019-08-20 20:00
![EnXIfTM](https://user-images.githubusercontent.com/7444510/63380001-8ca03900-c363-11e9-879c-e1e77bace348.png)

Okay got it figured it out, will be a bit more complicated but we'll see.
Basically create a 0 gap space into the region so it's a "hole"

**Comment by espidev** [comment] 2019-08-21 14:52
Okay the main functions are roughly done, just needs polish!

The merging performance is fine, but the worrying part is the performance of unmerging, since it gets more complicated where I figure out whether or not the region will split the parent region, as well as having to run the merge algorithm after the unmerged region is removed. I am unable to make this async as of yet, and I'm predicting that performance will start tanking (1s pause) at around maybe 50 merged regions with 128x128 radius for unmerging.

**Comment by espidev** [comment] 2019-08-21 22:52
Okay I've done quite a few tests, and I'd say that the feature has now fully been implemented.
![Screenshot_20190821_184907](https://user-images.githubusercontent.com/7444510/63473751-9a79bb00-c444-11e9-8683-70712f0fddb9.png)

The lines on dynmap are unavoidable since they are required for drawing regions with holes inside of them. @Leonardo-Fiori would you like to try this in production before release? I feel that it is ready, but extra feedback would be awesome!

**Comment by Leonardo-Fiori** [comment] 2019-08-22 00:06
@espidev wow finally!

Yeah I would absolutely love to try it, maybe before on a smaller test server that I always keep ready on Hetzner for testing purposes. Test it for a day, then move it to the main server. After the adequate backups of course..

But I have some considerations:

1) Is the unmerge algorithm still on the main thread? 

2) Is there an option to prevent regions with holes inside instead of cutting them like that? 

It could be a gameplay rule.. "don't claim leaving holes in your region". Like on the original factions plugin if I remember correctly. There is nothing wrong with it. :) And it would avoid that line in the dynmap.

3) I think that this will not be my case, but do you think that a WG region composed by so many points like the one you posted here in the picture would be more laggy than a simple cuboid?

This should not be an issue on my server tho, because I want to enable region merging only on bigger sized protection stones! And players have a limit on how many ps they can place.


And thank you for all the hard work ♥️

**Comment by espidev** [comment] 2019-08-22 02:02
> 1. Is the unmerge algorithm still on the main thread?

Yes, but from my testing, performance is okay, with performance hits (pause the server for 1s) when dealing with huge amounts of covered area (3000x3000) and many many protected regions inside with holes. Unfortunately, I can't get it off the main thread right now without breaking everything so at least for now, I'll continue work on optimizing the algorithm.

> 2. Is there an option to prevent regions with holes inside instead of cutting them like that?
> 
> It could be a gameplay rule.. "don't claim leaving holes in your region". Like on the original factions plugin if I remember correctly. There is nothing wrong with it. :) And it would avoid that line in the dynmap.

Yes, but I need to do more work :]
At this point, it would be more work and messy code to prevent holes but I can come back to that once the code is cleaned up. 

The line is actually zero area so it doesn't affect anything, it's just visual on dynmap.

> 3. I think that this will not be my case, but do you think that a WG region composed by so many points like the one you posted here in the picture would be more laggy than a simple cuboid?

Technically yes, but it shouldn't be noticeable unless we are talking about abnormally complex regions (like maybe hundreds to thousands of holes?). WorldGuard uses a fairly optimized algorithm to figure out whether or not you are in a complex region.

The code for the merging currently looks like a dumpster fire right now but it seems pretty stable right now. Of course, a lot of things changed, and I had to add a lot of new behaviour on how grouped regions handle other region tasks, so bug testing would be great!

You can get the beta here: https://ci.espi.dev/job/ProtectionStones/106/

**Comment by Leonardo-Fiori** [comment] 2019-08-22 11:07
Ok i started the testing. I will let you know :)

> Yes, but I need to do more work :]
> At this point, it would be more work and messy code to prevent holes but I can come back to that > once the code is cleaned up.

Yeah i can wait for you to polish the code and then implement this! :)

**Comment by Leonardo-Fiori** [comment] 2019-08-22 12:46
@espidev 

1) /ps view is too fps laggy, even for me with a 780Ti..
2) Players do not receive any message for merging regions when they place blocks, only me with the op.

**Comment by espidev** [comment] 2019-08-22 13:45
> 1. /ps view is too fps laggy, even for me with a 780Ti..

Yeah that's a work in progress... The particles are not very performant, I might just return back to blocks for now and attempt it again later.

> I tought that /ps merge was a command for administrators. You should totally make a /ps admin forcemerge to force the merge of all the regions in the world :)

The problem is that the plugin can't really decide which region settings to keep when merging.

Tomorrow I will be leaving on a 2 week trip where I might have time to use my laptop but I can only do maintenance really so I'll try and possibly release with this feature set (after a few more tweaks of course).

**Comment by espidev** [comment] 2019-08-22 13:49
> My timings so far.. we tried to abuse it very much lol
> Placing lots of PS and merging and unmerging.. so far nothing. But not many players partecipated to the test. I will call more to join soon.
> 
> https://timings.aikar.co/?id=1f210ac59ae448aa8ff4d89acbcbb8ee#config

The merging algorithm is performant as long as you have more than 1 core on your CPU lol. I see one of the unmerge steps take 2ms which is very good but I'm not sure how large of a region it was.

**Comment by Leonardo-Fiori** [comment] 2019-08-22 13:54
The command should be called force merge, lol

To use when lazy players that have been asked to merge, did not do anything.. just pick a random region from the blob, and merge on it.

I did not manage to find unmerge in the timings, i only see merge, that is very performant.

So enjoy your trip!

I will wait for you to clean this up and add the other features (prevent holes, force merge maybe, and the new request i made for bypassing adiacent limits)

**Comment by Leonardo-Fiori** [comment] 2019-08-22 14:17
I forgot to ask:

- Add an automatic merge option that can be toggled in the config, so it gets easier for players

- Implement also a minimum distance also between the protection stones that you own. To force players to spread their PS in a more even way. Maybe in the message you should print also the distance from the other protection stone.

- Limit the number of regions that can be merged? Is this a way to prevent lag spikes? Is the size of the region or the number of points that matters?

**Comment by espidev** [comment] 2019-08-22 14:19
> The command should be called force merge, lol
> 
> To use when lazy players that have been asked to merge, did not do anything.. just pick a random region from the blob, and merge on it.

Maybe if the flags were default. This could be added as a new issue.

> I did not manage to find unmerge in the timings, i only see merge, that is very performant.

What you see is most likely the unmerge algorithm because it needs to use WGMerge to re-run the merge process after a region is removed.

**Comment by espidev** [comment] 2019-08-22 14:21
> I forgot to ask:
> 
> * Add an automatic merge option that can be toggled in the config, so it gets easier for players

Should open a new issue

> * Implement also a minimum distance also between the protection stones that you own. To force players to spread their PS in a more even way. Maybe in the message you should print also the distance from the other protection stone.

Possible, you should open a new issue for it.

> * Limit the number of regions that can be merged? Is this a way to prevent lag spikes? Is the size of the region or the number of points that matters?

It's the number of points, since the algorithm currently traverses the edge of the region.

**Comment by Leonardo-Fiori** [comment] 2019-08-22 14:28
Ok.. maybe a cap for merging regions would be a better security measure to prevent spikes i guess?

Oh, and related to the automatic merging option, add it for each protection stones .toml

I will submit forcemerge

**Comment by espidev** [comment] 2019-08-22 14:48
Try this build, /ps view should be much better now: https://ci.espi.dev/job/ProtectionStones/110/

**Comment by espidev** [comment] 2019-08-22 14:48
If this works out, this will probably the one initially released for 2.4.0

**Comment by Leonardo-Fiori** [comment] 2019-08-22 15:13
I restarted the server with the new updated plugin and i got errors related to worlds .dat file.. could this be realted?

https://pastebin.com/c62CQvZy

**Comment by Leonardo-Fiori** [comment] 2019-08-22 15:16
Went from 600 fps to 100 when doing /ps view..

Ill test later with other players

**Comment by espidev** [comment] 2019-08-22 15:18
ProtectionStones shouldn't be able to do any actual chunk manipulation, were you testing in the nether?

**Comment by espidev** [comment] 2019-08-22 15:19
All that changed was /ps view

**Comment by Leonardo-Fiori** [comment] 2019-08-22 16:51
@espidev found a bug!

Players can override max protection stones permission simply merging multiple protection stones inside one..

Example:

- Limit is set to 10x coal.

- Places 10x coal.

- Merges 1 of them in another.

- Can place another 1x coal ps.

You have to store the count of how many ps a player has in another variable, i think. So it does not get subtracted when you merge.

**Comment by espidev** [comment] 2019-08-22 16:54
@Leonardo-Fiori thanks for reporting! Ill get a fix done in ~3-4 hours ish (away right now).

Yeah now getting player regions currently doesn't give decomposed regions so I'll have to add checks for that.

**Comment by espidev** [comment] 2019-08-22 22:35
I've fixed the issue, and I'm also going to release 2.4.0 now.

This means that I'll close the issue for now since the initial merging is done, and we can continue further discussion of more merge features in the other issues.

**Closed by espidev** 2019-08-22 22:35 UTC
Labels: enhancement
