### ISSUE TITLE
Exception on /ps admin cleanup

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#27] opened 2019-07-23 15:23 UTC
I have a new problem for you! When i do /ps admin cleanup remove 30 world i get an error and the cleanup does not work. 

[14:55:06 WARN]: Failed to load player data for bb16812c-d8c9-42f4-bbed-3c5ffad95c84
[14:55:07 WARN]: Failed to load player data for bb16812c-d8c9-42f4-bbed-3c5ffad95c84
[14:55:07 WARN]: [ProtectionStones] Plugin ProtectionStones v2.1.3 generated an exception while executing task 123709
java.lang.NullPointerException: null
at com.sk89q.worldguard.domains.PlayerDomain.contains(PlayerDomain.java:148) ~[?:?]
at com.sk89q.worldguard.domains.DefaultDomain.contains(DefaultDomain.java:245) ~[?:?]
at com.sk89q.worldguard.protection.regions.ProtectedRegion.isOwner(ProtectedRegion.java:281) ~[?:?]
at dev.espi.ProtectionStones.commands.ArgAdminCleanup.lambda$argumentAdminCleanup$1(ArgAdminCleanup.java:90) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-107]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.2.jar:git-Paper-107]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.2.jar:git-Paper-107]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
​
Just updated WG to WorldGuard 7.0.1-SNAPSHOT

This server is running Paper version git-Paper-107 (MC: 1.14.2)

**Comment by espidev** [comment] 2019-07-23 20:04
Duplicate of #24, issue being investigated

**Closed** 2019-07-23 20:04 UTC
Labels: bug, duplicate
