### ISSUE TITLE
prevent destroy world before placing protectionstones

### ISSUE THREAD

**Issue by SliderKP** [espidev/ProtectionStones#231] opened 2021-01-23 02:24 UTC
any way to prevent destroy/build in a world before the user place a protectionstone....

i tried to rg flag __global__ build deny and giving to user the permission: worldguard.build.block.place.iron_ore but... not working.

**Comment by espidev** [comment] 2021-01-23 03:20
duplicate of https://github.com/espidev/ProtectionStones/issues/197
i have not had any time to work on this feature so far

**Closed by espidev** 2021-01-23 03:20 UTC
